export enum SystemTypeCodes {
  CO2 = 'CO2',
  FLOW = 'FLOW',
  GAS = 'GAS',
  H2O = 'H2O',
  H2OM = 'H2OM',
  H2OT = 'H2OT',
  HCL = 'HCL',
  HF = 'HF',
  HG = 'HG',
  LTGS = 'LTGS',
  LTOL = 'LTOL',
  NOX = 'NOX',
  NOXC = 'NOXC',
  NOXE = 'NOXE',
  NOXP = 'NOXP',
  O2 = 'O2',
  OILM = 'OILM',
  OILV = 'OILV',
  OP = 'OP',
  PM = 'PM',
  SO2 = 'SO2',
  ST = 'ST',
}
