export class AppECorrelationTestSummaryBaseDTO {}

export class AppECorrelationTestSummaryRecordDTO extends AppECorrelationTestSummaryBaseDTO {}

export class AppECorrelationTestSummaryImportDTO extends AppECorrelationTestSummaryBaseDTO {}

export class AppECorrelationTestSummaryDTO extends AppECorrelationTestSummaryRecordDTO {}
